name: m18_residences_shared

on:
  push:
    branches: [main, development]
    paths: ['packages/m18_residences_shared/**', '.github/workflows/m18_residences_shared.yml']
  pull_request:
    paths: ['packages/m18_residences_shared/**', '.github/workflows/m18_residences_shared.yml']
  workflow_dispatch:

jobs:
  check:
    uses: whatever413y/.github/.github/workflows/flutter-package-check.yml@v1
    with:
      working-directory: packages/m18_residences_shared
